name: Git Collect
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Git Collect
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: work-design/engine
          ref: main
          submodules: true
          token: ${{ github.token }}
      - name: Git Pull
        run: |
          git config --global user.email 'mingyuan0715@foxmail.com'
          git config --global user.name 'Mingyuan Qin With Bot'
          git submodule foreach git checkout main
      - name: Changes
        run: |  
          git status
          git add .
          git commit -m 'up'
